name: Run Tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository's code

      - name: Install dependencies
        run: pip install pytest  # Install pytest

      - name: Run tests
        run: pytest ./test_hw2_debugging.py  # Run your tests